### ISSUE TITLE
Missing `sz::string::shrink_to_fit`

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/StringZilla#100]
The C layer defines the `sz_string_shrink_to_fit`, that is not covered by tests and is not yet used by the C++ API to implement the `shrink_to_fit`.

**Comment by Majeed-GitHub** [comment]
To address the issue in the "Stringzilla" project where the C layer implements sz_string_shrink_to_fit without test coverage and not utilized by the C++ API for shrink_to_fit, you can follow these steps to ensure proper implementation and integration:
Steps to Solve the Issue:
Unit Testing for sz_string_shrink_to_fit:
Write comprehensive unit tests specifically for the sz_string_shrink_to_fit function in the C layer to ensure its functionality is validated.
Integration with C++ API:
Modify the C++ API to utilize the sz_string_shrink_to_fit function for implementing shrink_to_fit. Update the C++ API codebase to incorporate this functionality.
Test Coverage:
Ensure that test coverage is extended to include the newly integrated functionality. Write tests in the C++ API that cover the usage of sz_string_shrink_to_fit for shrink_to_fit.
Cross-Language Testing:
Perform thorough testing to verify that the interaction between the C and C++ layers works seamlessly with the implementation of shrink_to_fit.
Code Review:
Conduct a code review to validate the changes made in both the C layer and the C++ API, ensuring adherence to best practices and maintaining code quality.
Documentation Update:
Update relevant documentation, including code comments and API documentation, to reflect the changes made regarding sz_string_shrink_to_fit and its usage in the C++ API.
Integration Testing:
Conduct integration testing to confirm that the shrink-to-fit functionality works correctly across both layers without any compatibility issues.
By following these steps, you can effectively address the lack of test coverage for sz_string_shrink_to_fit in the C layer and integrate it with the C++ API for implementing shrink_to_fit in the "Stringzilla" project.

**Comment by Riyazul555** [comment]
Hey @ashvardanian can you please explain this issue a more

**Comment by ashvardanian** [comment]
@Riyazul555, at the second glance, this issue is trickier then I thought, as I don't yet have a `sz_string_shrink_to_fit` implementation even in the C layer. It may not be a good fit for a beginner, but if you are interested, [cppreference.com describes the operation in more detail](https://en.cppreference.com/w/cpp/string/basic_string/shrink_to_fit).
