### ISSUE TITLE
[BUG] Instant error STATUS_ACCESS_VIOLATION on Windows with Rust lib 

### ISSUE THREAD

**Issue by 0xqd** [ashvardanian/StringZilla#116]
I got instant STATUS_ACCESS_VIOLATION while running the memchr_stringzilla benchmark, it works totally fine with WSL2 on Windows but not on Windows itself.

**Comment by 0xqd** [comment]
@ashvardanian The repo I use to reproduce is the one from you: 
https://github.com/ashvardanian/memchr_vs_stringzilla

Environment the script run on: 

```
cargo --version
cargo 1.76.0 (c84b36747 2024-01-18)

winver
Version 22H2 (OS Build 22621.1702)
```

**Comment by ashvardanian** [comment]
@0xqd What kind of Windows machine are you running on? Is that a  Aarch64 Arm-based machine by any chance?

**Comment by ashvardanian** [comment]
This might be coming from Rust itself, there is a similar issue reported for Arm-based Windows setups: https://github.com/rust-lang/rust/issues/118462

**Comment by 0xqd** [comment]
@ashvardanian it's x86_64 with Intel 13900K. Yeah I have seen that report, not sure if you have the solution.

**Comment by ashvardanian** [comment]
Is that issue still bothering you, @0xqd? I can try running it on a Windows machine later today 🤗

**Comment by 0xqd** [comment]
hi there @ashvardanian, instead of using Windows just for convenience, I switch everything to Linux to be problem free now.

**Comment by ashvardanian** [comment]
That should make your life easier down the road 🤗
