### ISSUE TITLE
[CLI] sz_split error

### ISSUE THREAD

**Issue by lborcard** [ashvardanian/StringZilla#139]
Thank you very much for sharing this great project.
I am using the cli tool sz_split and it's stopping after the first split when I specify  `-n 20` .
It produces only 1 of the 20 files and stops with this error message:
```
An error occurred: [Errno 0] Error: 'X0'
```

I am splitting a .fast5 (hdf5 files for sequencing data).
`sz_split -n 20   gxb03325_20240327_1204_FAX92537_X5_sequencing_run_no_sample_ac8a3c2b_b3c8a5e7.fast5`
best,

Loïc

**Comment by ashvardanian** [comment]
That's interesting, @lborcard! Thank you for submitting the issue?
Would it be possible to share the file URL or a simple test case that I can use to replicate the issue?

**Comment by lborcard** [comment]
I am pretty sure that the python split.py does not work with the `-n ` flag because it does work without any flags

**Comment by MarkReedZ** [comment]
@lborcard The split works for me.  Can you provide details on your machine?  OS ?

**Comment by MarkReedZ** [comment]
We should perhaps use logging.exception or traceback.    The error message above just prints the X0 filename - likely due to running out of disk space? 

https://stackoverflow.com/questions/1483429/how-do-i-print-an-exception-in-python

**Comment by ashvardanian** [comment]
@MarkReedZ sounds reasonable.

**Comment by lborcard** [comment]
> @lborcard The split works for me. Can you provide details on your machine? OS ?
Sorry for the late reply, I am working on centos 8

**Comment by ashvardanian** [comment]
Hi @lborcard! I've just tried using it with v3.9 and it works fine. Please let me know if the issue persists.
