### ISSUE TITLE
Empty substrings after .sort()

### ISSUE THREAD

**Issue by tescao** [ashvardanian/Stringzilla#14]
Hi, thanks for another awesome library!
I encountered some strange behavior while testing it, namely, .sort() method returns substrings that are empty except for the last word.

```python

from stringzilla import Str, File, Strs

sent = 'This trick has already saved me a few thousand dollars in the last couple of weeks.'
s_zilla = Str(sent).split()
s_zilla.sort()
for s in s_zilla:
    print(f"Substring:{s}, len: {len(s)}")
```

And the output is:

`
Substring:weeks., len: 6
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
Substring:, len: 0
`

**Comment by ashvardanian** [comment]
Oh wow, interesting! I will investigate! Thank you @tescao !

**Comment by ashvardanian** [comment]
@davvard has spotted and fixed the problem last week. Everything should work fine in v1.0.3. For ideal performance we need to find a way to compile multiple versions of the same function for different SIMD subsets and package them into the same wheel. @tescao, any chance you have experience with such things?
