### ISSUE TITLE
Bug: `sz_find_neon_too_smart` disagrees with `sz_find_neon`/`sz_find_serial`

### ISSUE THREAD

**Issue by hillelme** [ashvardanian/StringZilla#157]
### Describe the bug

Hi,

`sz_find_neon_too_smart` is disagreening with `sz_find_neon`/`sz_find_serial`
this happens in C, **only** with `n_length=2` (tested with lengths 1-32, and only "2" has this issue)

I noticed the first byte is equal where `sz_find_neon_too_smart` flagged, but the 2nd wasn't.

I used random strings of length `128` to compare the 2 functions.
```c
n[0]: 0xcb
n[1]: 0x7
n_length: 2
sz_find_neon: 64.            h[found_offset0]: 0xcb, h[found_offset0 + 1]: 0x7  <-- first and 2nd bytes good
sz_find_neon_too_smart: 60.  h[found_offset1]: 0xcb, h[found_offset1 + 1]: 0x30 <-- first byte good, 2nd not
```

Thanks!

### Steps to reproduce

haystack mem dump:
```c
0x80:     0x93    0xd9    0x96    0x3f    0xce    0xad    0xcf    0x48
0x88:     0xd8    0x2b    0x3     0x4a    0x8     0x5     0xe     0x8c
0x90:     0xf9    0xdc    0x6     0x3a    0x1     0x99    0x72    0x1e
0x98:     0xc6    0x5e    0xc1    0x23    0x5e    0x7c    0x98    0xdf
0xa0:     0xcf    0xe2    0x3f    0x28    0xc6    0x28    0xe1    0xec
0xa8:     0x64    0x8f    0x3a    0x3b    0xb4    0x7     0xfe    0xc8
0xb0:     0x95    0xd0    0xa1    0x9b    0x4b    0x24    0x90    0x50
0xb8:     0x32    0x95    0xa4    0x44    0xcb    0x30    0xf2    0xa   <-- 0xcb here, but not followed by 0x7
0xc0:     0xcb    0x7     0xc     0x65    0xa8    0x1c    0x6b    0x25  <-- substring was selected from this line
0xc8:     0xb0    0x13    0x22    0x88    0xba    0xd0    0xd3    0xdc
0xd0:     0xf1    0xc5    0x31    0x8b    0xf0    0xc9    0x34    0xe6
0xd8:     0x5e    0x5a    0x37    0xea    0x6e    0x1e    0x74    0xfb
0xe0:     0x87    0x84    0x45    0x22    0x42    0x9b    0x33    0x48
0xe8:     0xbc    0x44    0x8a    0xb9    0x29    0xa7    0x2     0xea
0xf0:     0xd     0x59    0xd3    0x6     0x4f    0x64    0x10    0xe8
0xf8:     0x4a    0x1a    0xe5    0xbc    0x2     0x99    0xce    0xd
```
needle mem dump:
```c
0xcb    0x7
```

### Expected behavior

`sz_find_neon_too_smart` should look at all needle bytes, not just the 1st one

### StringZilla version

v3.9.0

### Operating System

Ubuntu 22

### Hardware architecture

Arm

### Which interface are you using?

C implementation

### Are you open to being tagged as a contributor?

- [ ] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
The experimental kernels are not supposed to be correct, they are just idea drafts. Poor naming in my side. Is the sz_find reporting a correct result?

**Comment by hillelme** [comment]
the non experimental find works fine. thanks
