### ISSUE TITLE
Bug: modify method variable in const method

### ISSUE THREAD

**Issue by heheda123123** [ashvardanian/StringZilla#161]
### Describe the bug

https://github.com/ashvardanian/StringZilla/blob/44f169c656c81d15bc8fb10bf472a440b43cda5a/include/stringzilla/stringzilla.hpp#L1027
the below code is const method, but modify method variable
```
    reversed_iterator_for operator++(int) const noexcept {
        reversed_iterator_for temp = *this;
        --ptr_;
        return temp;
    }

    reversed_iterator_for &operator--() const noexcept {
        ++ptr_;
        return *this;
    }

    reversed_iterator_for operator--(int) const noexcept {
        reversed_iterator_for temp = *this;
        ++ptr_;
        return temp;
    }

```
will trigger build error
https://github.com/xmake-io/xmake-repo/actions/runs/10473228204/job/29004626628?pr=4996#step:5:150

### Steps to reproduce

in this pr
https://github.com/xmake-io/xmake-repo/pull/4996

### Expected behavior

build success

### StringZilla version

v3.8.5

### Operating System

ubuntu 22.04

### Hardware architecture

x86

### Which interface are you using?

C++ bindings

### Contact Details

nihaoaheheda@gmail.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Nice catch, @heheda123123! Pushing a patch in a bit ;)
