### ISSUE TITLE
Bug: build failed on windows arm 

### ISSUE THREAD

**Issue by heheda123123** [ashvardanian/StringZilla#163]
### Describe the bug

in this PR https://github.com/xmake-io/xmake-repo/pull/4846
the error message is 
```
C:\Users\runneradmin\AppData\Local\.xmake\packages\s\stringzilla\v3.8.4\805b129fea3949ae9b9e966212368884\include\stringzilla/stringzilla.h(1346): error C3861: '_tzcnt_u32': identifier not found
C:\Users\runneradmin\AppData\Local\.xmake\packages\s\stringzilla\v3.8.4\805b129fea3949ae9b9e966212368884\include\stringzilla/stringzilla.h(1347): error C3861: '_lzcnt_u32': identifier not found
```
the below issue and PR add condition macro to use other api maybe can fix this
https://github.com/opencv/opencv/issues/9250
https://github.com/opencv/opencv/issues/7626

### Steps to reproduce

in this PR https://github.com/xmake-io/xmake-repo/pull/4846

### Expected behavior

build success on windows arm

### StringZilla version

v3.8.4

### Operating System

windows arm

### Hardware architecture

x86

### Which interface are you using?

C++ bindings

### Contact Details

nihaoaheheda@gmail.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Nice catch again, @heheda123123! I am wondering why our CI doesn't notice those build issues. Any specific configs that you have set up differently?

**Comment by heheda123123** [comment]
I don't know if the xmake-repo repository has done any special configuration, I just add PR for my favorite packages.
Maybe you can look at the workflow he has setup
https://github.com/xmake-io/xmake-repo/tree/dev/.github/workflows
