### ISSUE TITLE
Bug: example code Assertion failed

### ISSUE THREAD

**Issue by heheda123123** [ashvardanian/StringZilla#164]
### Describe the bug

the example code in readme.md shows 

![image](https://github.com/user-attachments/assets/ec4ed27f-c157-4efc-a333-c755d0ada307)
```
str("a:b").back(-1) == "b"; // accepting negative indices
```
but the type for the argument is size_type(unsigned long long ), it can not hold negative number.
![image](https://github.com/user-attachments/assets/8b38d4be-608e-44ac-9e02-842e6a2592e8)

the source code has assert, but only take effect when build with debug mode 
If I build code in release mode, there is no error.

![image](https://github.com/user-attachments/assets/5bbd59bd-cdea-4bc1-88ca-17b96e20a2a3)
But when I switch to debug mode , will trigger assert to failed
![image](https://github.com/user-attachments/assets/136039a1-8294-4310-82cb-3bf4b35d0733)

### Steps to reproduce

I use 3.9.0, but the latest code is the same in below
```

#include <stringzilla/stringzilla.hpp>
namespace sz = ashvardanian::stringzilla;
using sz::literals::operator""_sz;

int main() {
   sz::string("a:b").back(-1) == "b";
    
}

```
build in debug mode
```
PS C:\Users\Administrator\temp\testzilla> xr
Assertion failed: n <= size() && "string_slice::back(n) out of bounds", file C:\Users\Administrator\.conan2\p\strine40c660b735ea\p\include\stringzilla/stringzilla.hpp, line 1264
error: @programdir\core\main.lua:329: @programdir\modules\async\runjobs.lua:325: @programdir\core\sandbox\modules\os.lua:378: execv(C:\Users\Administrator\temp\testzilla\build\windows\x64\debug\testzilla.exe ) failed(-1073740791)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [@programdir\core\sandbox\modules\os.lua:378]: in function 'execv'
    [@programdir\actions\run\main.lua:57]: in function '_do_run_target'
    [@programdir\actions\run\main.lua:76]: in function 'script'
    [@programdir\actions\run\main.lua:145]: in function '_run'
    [@programdir\actions\run\main.lua:251]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:241]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>
```

### Expected behavior

use the right argument type

### StringZilla version

v3.9.0

### Operating System

windows 11

### Hardware architecture

x86

### Which interface are you using?

C++ bindings

### Contact Details

nihaoaheheda@gmail.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
I believe [this commit](https://github.com/ashvardanian/StringZilla/commit/9889e066763f6f075ff70e0f0adcb3086923297a) solves the issue, @heheda123123. Please let me know, if it persists 🤗

**Comment by heheda123123** [comment]
thanks, problem solved
