### ISSUE TITLE
Feature: Python bytearray support on low-level API

### ISSUE THREAD

**Issue by marcoffee** [ashvardanian/StringZilla#166]
### Describe what you are looking for

Is there any plan to support `bytearray`s on low-level Python API methods?

They behave a lot like `bytes` but they are mutable (which allow using them as buffers on IO operations, etc), hence, they solve a lot of use-cases where you can't use `bytes`.

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
I was under impression that we already support them. Probably a good idea to add a test case. Extending should be very easy. Thanks for reporting, @marcoffee 🤗

**Comment by marcoffee** [comment]
Wow, that was really fast!

Thanks!! 🚀 🚀 🚀
