### ISSUE TITLE
Bug: MacOS CI produces x86 build instead of ARM

### ISSUE THREAD

**Issue by zekronium** [ashvardanian/StringZilla#167]
### Describe the bug

The provided release, `stringzillite_macos_arm64_3.9.4` actually produces an x86 file.

<img width="593" alt="image" src="https://github.com/user-attachments/assets/be9f973e-87a7-4b13-96fa-85cfca8c562e">

### Steps to reproduce

`file libstringzillite.dylib`

### Expected behavior

Should produce an arm build

### StringZilla version

v3.9.4

### Operating System

MacOS

### Hardware architecture

Arm

### Which interface are you using?

C implementation

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zekronium** [comment]
The CI should explicitly specify the target from x86 platforms.

```-target x86_64-apple-macos```.

Example usage: 
```cxx
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_ASM_FLAGS="-Wa,--noexecstack -target arm64-apple-macos11" \
      -DCMAKE_C_FLAGS_RELEASE="-O3 -fno-omit-frame-pointer -target arm64-apple-macos11" \
      -DCMAKE_CXX_FLAGS_RELEASE="-O3 -fno-omit-frame-pointer -target arm64-apple-macos11 -Wno-error=range-loop-analysis" \
      -DCMAKE_SYSTEM_PROCESSOR=arm64 \
      -DCMAKE_OSX_ARCHITECTURES=arm64 \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
      -GNinja ..
```

**Comment by ashvardanian** [comment]
Nice catch @zekronium! Any chance you could submit a PR?

**Comment by zekronium** [comment]
You think its worth it adding permissions to run CI for such a small change?

**Comment by ashvardanian** [comment]
I'd prefer to avoid changing project settings. Can try patching myself in a couple of days, if it's not urgent 🤗

**Comment by ashvardanian** [comment]
Assuming, absolutely majority of Mac's are based on Arm now, I've decided to deprecate x86 builds for now, and build for Arm by default. Let me know if x86 builds are still a high priority 🤗
