### ISSUE TITLE
Bug: C++ capacity test fails with MSVC x86 32-bit

### ISSUE THREAD

**Issue by ashbob999** [ashvardanian/StringZilla#168]
### Describe the bug

When building with MSVC for 32-bit, one of the C++ test assertions fail.

https://github.com/ashvardanian/StringZilla/blob/817f46953c632961b6ecca6d4f6343a0e82c0a37/scripts/test.cpp#L459

When running with `std::string`, due to `sz::string::min_capacity` being 10 in 32-bit mode, whilst the MSVC `std::string` SSO capacity is 15.

### Steps to reproduce

Build & run the C++ tests in 32-bit using MSVC.

### Expected behavior

C++ tests pass.

### StringZilla version

3.9.5

### Operating System

Windows 10

### Hardware architecture

x86

### Which interface are you using?

C implementation

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks @ashbob999!
