### ISSUE TITLE
Bug: Missing `string_view_less `, `string_view_hash`, `string_view_equal`

### ISSUE THREAD

**Issue by toge** [ashvardanian/StringZilla#175]
### Describe the bug

There are compilation errors on [Standard C++ Containers with String Keys](https://github.com/ashvardanian/StringZilla?tab=readme-ov-file#standard-c-containers-with-string-keys) on README.md

`sz::string_view_less`, `sz::string_view_hash` and `sz::string_view_equal` seem not to be defined.

### Steps to reproduce

```
#include <map>
#include <unordered_map>

#include "stringzilla/stringzilla.hpp"

int main() {
  auto a = std::map<ashvardanian::stringzilla::string, int>{};
  auto b = std::unordered_map<ashvardanian::stringzilla::string, int>{};
}
```

### Expected behavior

There are no compilation error.

### StringZilla version

3.9.6

### Operating System

Fedora Linux 40

### Hardware architecture

x86

### Which interface are you using?

C++ bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Sorry, @toge! Just saw this one, patching in a minute 🤗
