### ISSUE TITLE
Bug: Heap-Buffer-Overflow in _sz_find_3byte_serial

### ISSUE THREAD

**Issue by Keynib** [ashvardanian/StringZilla#177]
### Describe the bug

I have used StringZilla in private project and Address Sanitizer has reported Heap-Buffer-Overflow error in `_sz_find_3byte_serial` function.

```
==2509==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000d473 at pc 0x560a2491eac3 bp 0x7fffd97c3a60 sp 0x7fffd97c3a50
READ of size 1 at 0x60200000d473 thread T0
    #0 0x560a2491eac2 in _sz_find_3byte_serial /root/.conan2/p/strin3bc98f8dde580/p/include/stringzilla/stringzilla.h:2132
    #1 0x560a2493cd67 in sz_find_serial /root/.conan2/p/strin3bc98f8dde580/p/include/stringzilla/stringzilla.h:2369
    #2 0x560a2493cd67 in sz_find /root/.conan2/p/strin3bc98f8dde580/p/include/stringzilla/stringzilla.h:6390
...

Shadow bytes around the buggy address:
  0x60200000d180: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x60200000d200: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x60200000d280: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x60200000d300: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fd
  0x60200000d380: fa fa fd fd fa fa fd fd fa fa fd fa fa fa fd fa
=>0x60200000d400: fa fa fd fd fa fa fd fd fa fa 00 00 fa fa[03]fa
  0x60200000d480: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fa fa
  0x60200000d500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200000d580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200000d600: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200000d680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2509==ABORTING
```
I have checked to the code and found that `_sz_find_3byte_serial` expects that needle has 3 bytes length. But when this string passes to sz_u64_vec_t, the code tries to access to fourth byte:
```
    // We fetch 12
    sz_u64_vec_t h0_vec, h1_vec, h2_vec, h3_vec, h4_vec;
    sz_u64_vec_t matches0_vec, matches1_vec, matches2_vec, matches3_vec, matches4_vec;
    sz_u64_vec_t n_vec;
    n_vec.u64 = 0;
    n_vec.u8s[0] = n[0], n_vec.u8s[1] = n[1], n_vec.u8s[2] = n[2], n_vec.u8s[3] = n[3];
``` 
So if we pass to this function std::string_view with length equals 3, n[3] goes beyond the boundaries of the array.

### Steps to reproduce

I tried to reproduce this bug though local unit tests, but get failed. I suppose you can try to allocate memory with length 3 on heap and pass it to the function.

### Expected behavior

The solution of this problem is removing the work with fourth byte if three-length string. It have tested it locally and unit tests have finished well:
```
Hi, dear tester! You look nice today!
- Uses AVX2: no 
- Uses AVX512: no 
- Uses NEON: no 
- Uses SVE: no 
All tests passed... Unbelievable!
```

I suppose the correct code line in this case is:
```
n_vec.u8s[0] = n[0], n_vec.u8s[1] = n[1], n_vec.u8s[2] = n[2];
```

### StringZilla version

v3.10.0

### Operating System

Ubuntu 22.04

### Hardware architecture

x86

### Which interface are you using?

C implementation

### Contact Details

keyn409@gmail.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Great catch, thank you! Can patch in an hour 🤗
