### ISSUE TITLE
Feature: Build C only library

### ISSUE THREAD

**Issue by nordlow** [ashvardanian/StringZilla#183]
### Describe what you are looking for

I'd like to be able to use this from the D programming language via `extern(C)` declarations.

In order to do that I need to build a C-only object or library.

It would be awesome if I could do this via a call to `make SOME_C_LIBRARY_TARGET` after the call to cmake has been done and get either a .o, .a or .so file built using the preferred compiler and compilation flags.

In the mean time, is building a C-only library preferrably done using

```sh
"${CC}" -c -O3 -march=native -Iinclude c/lib.c -o libstringzilla.o
```

?

Btw, is it preferred to compile with `${CC}` being either GCC or Clang? I'm asking because I noticed Clang-related warnings when building with GCC that aren't shown when building with Clang. I'm on Ubuntu 24.04.

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

C implementation

### Contact Details

per.nordlow@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@nordlow, [those targets exist](https://github.com/ashvardanian/StringZilla/blob/0f762add5dc3da13dbe650fb46533777f0821f4a/CMakeLists.txt#L342-L349):

```cmake
  define_shared(stringzilla_shared)
  target_compile_definitions(stringzilla_shared PRIVATE "SZ_AVOID_LIBC=0")
  target_compile_definitions(stringzilla_shared PRIVATE "SZ_OVERRIDE_LIBC=1")

  # Try compiling a version without linking the LibC
  define_shared(stringzillite)
  target_compile_definitions(stringzillite PRIVATE "SZ_AVOID_LIBC=1")
  target_compile_definitions(stringzillite PRIVATE "SZ_OVERRIDE_LIBC=1")
```

To builds, use:

```sh
cmake -B build_release && cmake --build build_release --config Release --target stringzilla_shared
```

**Comment by nordlow** [comment]
Thank you! I'm fine with simply compiling and linking an .o file for now.
