### ISSUE TITLE
Bug: building from sdist fails, missing VERSION file on PyPI

### ISSUE THREAD

**Issue by ccoulombe** [ashvardanian/StringZilla#186]
### Describe the bug

When building from PyPI from the sdist, it fails with:
```
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

as there's no `VERSION` file in the sdists:
```
$ tar --list -f stringzilla-3.10.5.tar.gz | fgrep -i version
$ 
```

Note that the file is present in the release on GH, just not on PyPI!
```
$ unzip -v v3.10.5.zip | fgrep -i version
       7  Stored        7   0% 10-19-2024 04:51 251c2d22  StringZilla-3.10.5/VERSION
```

### Steps to reproduce

Install from the sdists

### Expected behavior

Build from source correctly, the VERSION file should be provided.

### StringZilla version

3.10.5

### Operating System

Centos

### Hardware architecture

x86

### Which interface are you using?

C++ bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
I've made a syntax error filling the `MANIFEST.in` both here and in SimSIMD 🤦 Should be fine now. Thanks for spotting, @ccoulombe!
