### ISSUE TITLE
When  I use chinese string to test bechmark, the performance is lower than python method

### ISSUE THREAD

**Issue by ybingHuang** [ashvardanian/StringZilla#56]
python scripts/bench.py --haystack_pattern "你好，StringZilla" --haystack_length 1e9 --needle "你好abce"  

![stringlizza](https://github.com/ashvardanian/StringZilla/assets/45745588/9c1a4c19-09d4-4983-b803-ede2148ad764)

**Comment by ashvardanian** [comment]
@ybingHuang that is possible with your haystack. It fully benefits the Python string and completely disregards my optimizations. I have already tested an improved approach in another repo and will try to release it this month.

**Comment by ybingHuang** [comment]
I am looking forward to the update ,thank you!

**Comment by ashvardanian** [comment]
Hi, @ybingHuang! It's not the case anymore on the `main-dev`. Looking forward to release it soon.
