### ISSUE TITLE
[Query] to read a large text file with delimited of size 75 GB

### ISSUE THREAD

**Issue by crbsram** [ashvardanian/StringZilla#65]
Hi Ash
Sorry for the Spam if the query is answered already.
Here is my usecase.
I have file of size 75GB which has 500mil lines.
For every line i need to scan 500mil lines to run some checks and prepare a result.
sorting is not required in our case.
we have a modern hardware with 64 cores and 512gb RAM with nvme ssd with 10GB/sec IOPS.
I would like to leverage the featurs of modern hardware than the traditional approach.
Infact I have loaded these in a postgres DB but running these with 100 parallel connection
takes huge time to iterate on 500mil records.
After looking at the talk on youtube, want to explore that stringzilla framework will be fit for our usecase.
Please let us know any pointers on the same.
Also if it is possible through stringzilla, are there any sample reference implementation to start with please let me know.
Thanks

Thanks
C.R.Bala

**Comment by ashvardanian** [comment]
Hi, @crbsram, thanks for reaching out! Everything depends on the complexity of your checks, but I don't see a reason why this wouldn't work with StringZilla.

How long are your rows on average?
Does your CPU support AVX-512?

**Comment by ashvardanian** [comment]
Yes, @crbsram! This sounds like a good case for StringZilla. I'll have to warn you that even with StringZilla 5e6 x 5e6 pairwise string operations won't be very fast. I recommend setting up a smaller benchmark first. Let me know if this works out. 

What is the larger goal you are trying to achieve? Is that search?

**Comment by ashvardanian** [comment]
Hi @crbsram! How is it going? Any preliminary results?
