### ISSUE TITLE
Rust Bindings

### ISSUE THREAD

**Issue by michaelgrigoryan25** [ashvardanian/StringZilla#73]
Continuation of #66.

**Comment by michaelgrigoryan25** [comment]
@ashvardanian regarding the ranges in the table that you've shared in the PR, is it the same as sz_hash?

**Comment by ashvardanian** [comment]
Not the same, but related. Fingerprints are rolling hashes, which are used to populate a bitset.

**Comment by michaelgrigoryan25** [comment]
In that case which is the function for generating fingerprints using StringZilla?

**Comment by ashvardanian** [comment]
@michaelgrigoryan25, it's called [sz_fingerprint_rolling](https://github.com/ashvardanian/StringZilla/blob/2c13c58594c931e8c4a0ea029ecf32ec22fd22b9/include/stringzilla/stringzilla.h#L3971) 🤗

**Comment by michaelgrigoryan25** [comment]
These are the most commonly used string types in Rust:
- `&str`
- `String`
- `&String`
- `Cow<'_, str>`
- `Cow<'_, String>`

**Comment by michaelgrigoryan25** [comment]
These are the most commonly used string types in Rust:
- `&str`
- `String`
- `&String`
- `Cow<'_, str>`
- `Cow<'_, String>`

I can implement a macro which implements a common trait for all these types, so that methods like `sz_find` can be accessed directly, by only importing the trait via `use`.

**Comment by ashvardanian** [comment]
Sure. How about the `AsRef<[u8]>` I currently use?

**Comment by michaelgrigoryan25** [comment]
That would work.

**Comment by michaelgrigoryan25** [comment]
@ashvardanian https://github.com/michaelgrigoryan25/StringZilla/commit/4f4ace3e165886636f946252d1100c689fdce80a

**Comment by ashvardanian** [comment]
@michaelgrigoryan25 this looks good! Want to open a PR or want to add a few more things before that?

**Comment by michaelgrigoryan25** [comment]
Sure, let's do it right now.

**Comment by ashvardanian** [comment]
Thanks a lot, great patches, @michaelgrigoryan25! In C++ I've implemented lazy-evaluated convenience functions, like `find_all`, `rfind_all`, `split_all`, `rsplit_all`, and so on. [Took around 400 lines of code](https://github.com/ashvardanian/StringZilla/blob/20e41229e3fd4a143439d2268929674fc0cea0c8/include/stringzilla/stringzilla.hpp#L345-L733). I think it might be a great idea to implement them in Rust as well. What do you think? Would you be interested in adding those and the Levenshtein / Needleman-Wunsch alignment scores??

**Comment by michaelgrigoryan25** [comment]
@ashvardanian definitely, let's do it!

**Comment by ashvardanian** [comment]
As mentioned in #79, I am not sure about the right course of action here. The other operations, like #82 or random string generation might be more relevant. We should also benchmark against memchr and other native Rust string projects.

**Comment by ashvardanian** [comment]
[Benchmarks are ready](https://github.com/ashvardanian/memchr_vs_stringzilla).
