### ISSUE TITLE
Add search/split iterators for Rust

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/StringZilla#79]
In C++ we have special smart iterators for bulk search and split operations. They lazily report the matches, avoiding heap allocations for the array of match offsets.

For that, an arbitrary [matcher (string / character / character set ; in normal / reverse order)](https://github.com/ashvardanian/StringZilla/blob/06423189e7a5b9e2882b471e98ec897d40734fc4/include/stringzilla/stringzilla.hpp#L320-L400) is combined with [search / split ranges](https://github.com/ashvardanian/StringZilla/blob/06423189e7a5b9e2882b471e98ec897d40734fc4/include/stringzilla/stringzilla.hpp#L402-L790). Similar functionality should be added in Rust.

**Comment by ashvardanian** [comment]
Assuming search and split operations are lazy by default on native strings, I’m wondering if there is a way to avoid reimplementing those operations and still benefit from SZ speeds.

**Comment by grouville** [comment]
Would you be interested in me investigating this issue ? I can come up with a proposal as a draft PR too

**Comment by ashvardanian** [comment]
Yes, @grouville, that can be very useful, thank you!
