### ISSUE TITLE
Add search/split iterators for Python

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/StringZilla#80]
In C++ we have special smart iterators for bulk search and split operations. They lazily report the matches, avoiding heap allocations for the array of match offsets.

For that, an arbitrary [matcher (string / character / character set ; in normal / reverse order)](https://github.com/ashvardanian/StringZilla/blob/06423189e7a5b9e2882b471e98ec897d40734fc4/include/stringzilla/stringzilla.hpp#L320-L400) is combined with [search / split ranges](https://github.com/ashvardanian/StringZilla/blob/06423189e7a5b9e2882b471e98ec897d40734fc4/include/stringzilla/stringzilla.hpp#L402-L790). Similar functionality should be added in Python, where we currently materialize the matches into a "compressed" `Strs` object.

**Comment by ghazariann** [comment]
I'm very interested in contributing to this project as my first step into open-source. I believe I could start by addressing this issue. To clarify, are we aiming to replace the Strs type with something like StrIterator that yields strings lazily? As a first step, should I focus on modifying the split function to eliminate the use of realloc and ensure it returns an iterator instead? Any guidance on this would be greatly appreciated.

**Comment by ashvardanian** [comment]
Added in 3b6cdddbcba50b326eb44fa799381b978d99bdc5
