### ISSUE TITLE
Expose Levenshtein distance and NW to Rust

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/StringZilla#82]
Unlike C, C++, Swift, and Python, the Rust interface lacks any exposure to `sz_edit_distance` and `sz_alignment_score`, which might be of interest to many users.

**Comment by michaelgrigoryan25** [comment]
I will pick this up. Are these the correct definitions of the above mentioned functions?
- https://github.com/ashvardanian/StringZilla/blob/main/c/lib.c#L258
- https://github.com/ashvardanian/StringZilla/blob/main/c/lib.c#L265

**Comment by michaelgrigoryan25** [comment]
Also, for now, which branch should I use for the upstream of my PR, `main` or `main-dev`?

**Comment by ashvardanian** [comment]
Yes, those are!

**Comment by michaelgrigoryan25** [comment]
We can close this now.

**Comment by grouville** [comment]
@ashvardanian hasn't it been fixed by https://github.com/ashvardanian/StringZilla/pull/89 ?

**Comment by ashvardanian** [comment]
Yes, @grouville, you are right! For some reason the CI didn't close this 🤷‍♂️
