### ISSUE TITLE
Documentation is incorrect? `sz_string_append` does not exist

### ISSUE THREAD

**Issue by Frityet** [ashvardanian/StringZilla#87]
In the readme, a function named `sz_string_append` is referenced, but looking through the source code, its not defined at all, and I cannot use it in any code

**Comment by ashvardanian** [comment]
You are right! It was superseded by the expand API, and the docs fell behind. Can you please open a PR to refresh those? Thanks!

**Comment by Frityet** [comment]
Will do, I am currently adding Lua bindings to this library, and that will be in a later PR aswell

**Comment by ashvardanian** [comment]
Might be a good idea to split into separate smaller PRs, what do you think @Frityet?

**Comment by Frityet** [comment]
> Might be a good idea to split into separate smaller PRs, what do you think @Frityet?

yeah, that is better, I'm still tryna get a hand with the new API (i don't see any documentation, so i am just doing testing) so it will be a bit

**Comment by ashvardanian** [comment]
What do you mean by the lack of docs? I believe the header is quite extensively documented 🤷‍♂️
